name: PollExiled Build
on:
  push:
    branches:
    - main
    - dev
  pull_request:
    branches:
    - main
    - dev
  workflow_dispatch:
env:
  #Let's do discord host this file.
  REFERENCES_URL: https://cdn.discordapp.com/attachments/1081286605165318165/1114039667415859250/Libs.zip
  REFERENCES_PATH: ${{ github.workspace }}/References
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3

      - uses: actions/checkout@v3.3.0

      - name: Restore Packages
        run: nuget restore

      - name: Get Build References
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri ${{ env.REFERENCES_URL }} -OutFile ${{ github.workspace }}/Libs.zip
          Expand-Archive -Path Libs.zip -DestinationPath ${{ env.REFERENCES_PATH }}

      - name: Setup MSBuild.exe
        uses: microsoft/Setup-MSBuild@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Build
        run: | 
          msbuild ./Polls/Polls.csproj -t:rebuild -property:Configuration=Release -property:ReferencePath="${{ env.REFERENCES_PATH }}"

        #I start to wonder why the fuck is It work sometime, broken sometime.
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Poll Development Build
          path: "./bin/Release/Polls.dll"
